"""Initial migration

Revision ID: d6c5902e84d4
Revises: 
Create Date: 2026-07-16 03:04:40.872471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c5902e84d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('production_run_id', sa.String(), nullable=True),
    sa.Column('shot_id', sa.String(), nullable=True),
    sa.Column('artifact_type', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_ledgers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('production_run_id', sa.String(), nullable=True),
    sa.Column('maximum_units', sa.Integer(), nullable=True),
    sa.Column('used_units', sa.Integer(), nullable=True),
    sa.Column('reserved_units', sa.Integer(), nullable=True),
    sa.Column('available_units', sa.Integer(), nullable=True),
    sa.Column('saved_units', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('continuity_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('show_id', sa.String(), nullable=True),
    sa.Column('episode_id', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('field', sa.String(), nullable=True),
    sa.Column('previous_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('continuity_version', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=True),
    sa.Column('show_id', sa.String(), nullable=True),
    sa.Column('episode_id', sa.String(), nullable=True),
    sa.Column('production_run_id', sa.String(), nullable=True),
    sa.Column('shot_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_entries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('budget_ledger_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('shot_id', sa.String(), nullable=True),
    sa.Column('attempt_id', sa.String(), nullable=True),
    sa.Column('units', sa.Integer(), nullable=True),
    sa.Column('entry_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['budget_ledger_id'], ['budget_ledgers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workspace_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('premise', sa.String(), nullable=True),
    sa.Column('target_audience', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('default_aspect_ratio', sa.String(), nullable=True),
    sa.Column('default_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('default_style_profile_id', sa.String(), nullable=True),
    sa.Column('default_audio_profile_id', sa.String(), nullable=True),
    sa.Column('current_continuity_version', sa.Integer(), nullable=True),
    sa.Column('cover_artifact_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shows_slug'), 'shows', ['slug'], unique=True)
    op.create_table('characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('show_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('canonical_description', sa.String(), nullable=True),
    sa.Column('personality_traits', sa.JSON(), nullable=True),
    sa.Column('signature_behaviors', sa.JSON(), nullable=True),
    sa.Column('visual_constraints', sa.JSON(), nullable=True),
    sa.Column('default_wardrobe', sa.JSON(), nullable=True),
    sa.Column('color_palette', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('show_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('canonical_description', sa.String(), nullable=True),
    sa.Column('visual_constraints', sa.JSON(), nullable=True),
    sa.Column('reference_artifact_ids', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('show_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('animation_style', sa.String(), nullable=True),
    sa.Column('canonical_prompt', sa.String(), nullable=True),
    sa.Column('negative_prompt', sa.String(), nullable=True),
    sa.Column('color_palette', sa.JSON(), nullable=True),
    sa.Column('lighting_rules', sa.JSON(), nullable=True),
    sa.Column('camera_rules', sa.JSON(), nullable=True),
    sa.Column('motion_rules', sa.JSON(), nullable=True),
    sa.Column('texture_rules', sa.JSON(), nullable=True),
    sa.Column('reference_artifact_ids', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_references',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=True),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('artifact_id', sa.String(), nullable=True),
    sa.Column('is_canonical', sa.Boolean(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('show_id', sa.String(), nullable=True),
    sa.Column('season_number', sa.Integer(), nullable=True),
    sa.Column('episode_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('input_type', sa.String(), nullable=True),
    sa.Column('creative_input', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('target_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('aspect_ratio', sa.String(), nullable=True),
    sa.Column('style_profile_id', sa.String(), nullable=True),
    sa.Column('audio_profile_id', sa.String(), nullable=True),
    sa.Column('base_continuity_version', sa.Integer(), nullable=True),
    sa.Column('approved_production_run_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.ForeignKeyConstraint(['style_profile_id'], ['style_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('props',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('show_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('canonical_description', sa.String(), nullable=True),
    sa.Column('visual_constraints', sa.JSON(), nullable=True),
    sa.Column('reference_artifact_ids', sa.JSON(), nullable=True),
    sa.Column('current_owner_character_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['current_owner_character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['shows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episode_characters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=True),
    sa.Column('character_id', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('episode_wardrobe', sa.JSON(), nullable=True),
    sa.Column('episode_state_override', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('episode_locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('usage', sa.String(), nullable=True),
    sa.Column('episode_override', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('episode_id', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('current_stage', sa.String(), nullable=True),
    sa.Column('budget_limit', sa.Integer(), nullable=True),
    sa.Column('budget_used', sa.Integer(), nullable=True),
    sa.Column('retry_reserve', sa.Integer(), nullable=True),
    sa.Column('workflow_version', sa.String(), nullable=True),
    sa.Column('planning_prompt_version', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('production_run_id', sa.String(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('story_function', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('style_profile_version', sa.Integer(), nullable=True),
    sa.Column('approved_storyboard_artifact_id', sa.String(), nullable=True),
    sa.Column('approved_keyframe_artifact_id', sa.String(), nullable=True),
    sa.Column('approved_video_artifact_id', sa.String(), nullable=True),
    sa.Column('maximum_image_attempts', sa.Integer(), nullable=True),
    sa.Column('maximum_video_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('characters', sa.JSON(), nullable=True),
    sa.Column('camera', sa.JSON(), nullable=True),
    sa.Column('environment', sa.JSON(), nullable=True),
    sa.Column('continuity_requirements', sa.JSON(), nullable=True),
    sa.Column('keyframe_prompt', sa.String(), nullable=True),
    sa.Column('motion_prompt', sa.String(), nullable=True),
    sa.Column('negative_prompt', sa.String(), nullable=True),
    sa.Column('audio_cues', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['production_run_id'], ['production_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('production_run_id', sa.String(), nullable=True),
    sa.Column('shot_id', sa.String(), nullable=True),
    sa.Column('operation', sa.String(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('compiled_prompt', sa.String(), nullable=True),
    sa.Column('negative_prompt', sa.String(), nullable=True),
    sa.Column('reference_artifact_ids', sa.JSON(), nullable=True),
    sa.Column('provider_request_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('media_units', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result_artifact_id', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['production_run_id'], ['production_runs.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('artifact_id', sa.String(), nullable=True),
    sa.Column('production_run_id', sa.String(), nullable=True),
    sa.Column('shot_id', sa.String(), nullable=True),
    sa.Column('review_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('failures', sa.JSON(), nullable=True),
    sa.Column('retry_recommended', sa.Boolean(), nullable=True),
    sa.Column('retry_instruction', sa.JSON(), nullable=True),
    sa.Column('review_model', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['production_run_id'], ['production_runs.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quality_reports')
    op.drop_table('generation_attempts')
    op.drop_table('shots')
    op.drop_table('production_runs')
    op.drop_table('episode_locations')
    op.drop_table('episode_characters')
    op.drop_table('props')
    op.drop_table('episodes')
    op.drop_table('character_references')
    op.drop_table('style_profiles')
    op.drop_table('locations')
    op.drop_table('characters')
    op.drop_index(op.f('ix_shows_slug'), table_name='shows')
    op.drop_table('shows')
    op.drop_table('budget_entries')
    op.drop_table('workspaces')
    op.drop_table('workflow_events')
    op.drop_table('continuity_events')
    op.drop_table('budget_ledgers')
    op.drop_table('artifacts')
    # ### end Alembic commands ###
