import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { WizardShell, WizardTitle, Field, TextArea, SelectInput } from '../components/WizardShell'
import { generateShowProposal, generateIdea } from '../data/api'

const GENRES = ['Relationship drama', 'Heist thriller', 'Family secrets', 'Underdog sports', 'Workplace comedy', 'Cozy mystery']
const TONES = ['Dramatic with comedic justice', 'Suspenseful and slick', 'Warm and nostalgic', 'Fast and chaotic', 'Deadpan and dry']
const STYLES = ['Polished 3D', 'Cinematic Stylized 3D', 'Painterly 2D', 'Retro cel animation']

export function CreateShowBasicsScreen() {
  const navigate = useNavigate()
  const [loading, setLoading] = useState(false)
  const [sparking, setSparking] = useState(false)
  const [sparkSource, setSparkSource] = useState<string | null>(null)
  const [formData, setFormData] = useState({
    genre: 'Relationship drama',
    animation_style: 'Polished 3D',
    tone: 'Dramatic with comedic justice',
    target_audience: 'Global short-form viewers',
    default_duration_seconds: 45,
    idea_seed: ''
  })

  const handleSpark = async () => {
    setSparking(true)
    setSparkSource(null)
    try {
      const result = await generateIdea(formData.genre, formData.tone)
      setFormData({ ...formData, idea_seed: result.idea })
      setSparkSource(result.source)
    } catch (err) {
      console.error(err)
      setSparkSource('error')
    } finally {
      setSparking(false)
    }
  }

  const handleGenerate = async () => {
    if (!formData.idea_seed) return
    setLoading(true)
    try {
      const proposal = await generateShowProposal(formData)
      // Pass the generated proposal to the next screen
      navigate('/create-show/style', { state: { proposal } })
    } catch (err) {
      console.error(err)
      alert("Failed to generate proposal")
      setLoading(false)
    }
  }

  return (
    <WizardShell
      step={1}
      footerRight={
        <button
          onClick={handleGenerate}
          disabled={loading || !formData.idea_seed}
          className="flex items-center gap-2.5 rounded-lg bg-ink px-6 py-3 text-[15px] font-medium text-app transition-colors hover:bg-ink-2 disabled:opacity-50"
        >
          {loading ? 'qwen-max is building your show…' : 'Continue'}
          <svg width="16" height="16" viewBox="0 0 20 20" fill="none">
            <path d="M4 10h12M11 4.5L16.5 10 11 15.5" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
        </button>
      }
    >
      <WizardTitle title="Give your stories a world" subtitle="Provide a creative seed, and our AI will build the show universe for you." info />
      <div className="mx-auto max-w-[680px] px-6">
        <div className="grid grid-cols-2 gap-6">
          <Field label="Genre">
            <SelectInput
              value={formData.genre}
              options={GENRES}
              onChange={(v) => setFormData({...formData, genre: v})}
            />
          </Field>
          <Field label="Tone">
            <SelectInput
              value={formData.tone}
              options={TONES}
              onChange={(v) => setFormData({...formData, tone: v})}
            />
          </Field>
        </div>

        <div className="grid grid-cols-2 gap-6">
          <Field label="Animation Style">
            <SelectInput
              value={formData.animation_style}
              options={STYLES}
              onChange={(v) => setFormData({...formData, animation_style: v})}
            />
          </Field>
          <Field label="Default episode length">
            <SelectInput
              value={formData.default_duration_seconds.toString()}
              options={['30', '45', '60', '90']}
              onChange={(v) => setFormData({...formData, default_duration_seconds: parseInt(v)})}
            />
          </Field>
        </div>

        <Field label="Idea Seed">
          <TextArea
            value={formData.idea_seed}
            onChange={(v) => setFormData({...formData, idea_seed: v})}
            placeholder="e.g. A fruit character gets blamed for something they didn't do — or press Spark an idea below"
            rows={4}
          />
          <div className="mt-3 flex items-center justify-between">
            <p className="text-[13px] text-ink-4">
              {sparking
                ? 'qwen-max is pitching an idea…'
                : sparkSource === 'qwen-max'
                  ? 'Idea generated by qwen-max — spark again for another.'
                  : sparkSource === 'error'
                    ? 'Could not reach the idea engine — try again.'
                    : 'No idea yet? Pick a genre and tone above, then let the showrunner pitch you one.'}
            </p>
            <button
              type="button"
              onClick={handleSpark}
              disabled={sparking}
              className="flex shrink-0 items-center gap-2 rounded-lg border border-accent-border px-4 py-2 text-[14px] font-medium text-accent transition-colors hover:bg-accent/10 disabled:opacity-50"
            >
              <svg width="15" height="15" viewBox="0 0 20 20" fill="none">
                <path d="M10 2l1.8 4.6L16.5 8l-4.7 1.4L10 14l-1.8-4.6L3.5 8l4.7-1.4L10 2z" fill="currentColor" />
                <path d="M15.5 12.5l.9 2.3 2.1.7-2.1.7-.9 2.3-.9-2.3-2.1-.7 2.1-.7.9-2.3z" fill="currentColor" opacity="0.7" />
              </svg>
              {sparking ? 'Sparking…' : formData.idea_seed ? 'Spark another' : 'Spark an idea'}
            </button>
          </div>
        </Field>
      </div>
    </WizardShell>
  )
}

